{ config, pkgs, lib, ... }:
{
  wayland.windowManager.hyprland = {
    enable = true;
    # set the flake package
    # package = inputs.hyprland.${pkgs.stdenv.hostPlatform.system}.hyprland;
    # portalPackage = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.xdg-desktop-portal

    settings = {
      autogenerated = 0;

      monitor = [
        "eDP-1, 1920x1200@60, 0x0, 1"
	"monitor = , preferred, auto, auto"
      ];

      "$mainMod" = "SUPER";
      "$terminal" = "kitty";
      "$fileManager" = "thunar";
      "$menu" = "rofi -show drun";
      "$calc" = "rofi -show calc -calc-command-history";

      exec-once = [
        "dbus-update-activation-environment -- systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP"
	"waypaper --restore"
	"hyprpanel"
	"hypridle"
	"playerctld"
      ];

      env = [
        "QT_QPA_PLATFORMTHEME,qt6ct"
	"QT_QPA_PLATFORM=wayland"

        "XCURSOR_SIZE, 24"
	"HYPRCURSOR_SIZE, 24"
      ];

      exec = [
        "gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'" # for GTK4 apps

	"gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'" # for GTK3 apps
      ];

      general = {
        gaps_in = 0;
	gaps_out = 0;

	border_size = 1;

	resize_on_border = false;

	allow_tearing = false;

	layout = "dwindle";
      };

      decoration = {
        rounding = 5;

	active_opacity = "1.0";
	inactive_opacity = "0.9";

	shadow = {
	  enabled = false;
	};

	blur = {
	  enabled = true;
	  size = 3;
	  passes = 1;

	  vibrancy = "0.1696";
	};
      };

      animations = {
        enabled = true;

	bezier = [
	  "myBezier, 0.05, 0.9, 0.1, 1.05"
	];

	animation = [
	  "windows, 1, 7, myBezier"
	  "windowsOut, 1, 7, default, popin 80%"
	  "border, 1, 10, default"
	  "borderangle, 1, 8, default"
	  "fade, 1, 7, default"
	  "workspaces, 1, 6, default"
	];
      };

      dwindle = {
        pseudotile = false;
	preserve_split = true;
	force_split = 2;
	permanent_direction_override = true;
      };

      master = {
        new_status = "master";
      };

      misc = {
        force_default_wallpaper = -1;
	disable_hyprland_logo = false;
      };

      input = {
        kb_layout = "us, de";
	kb_variant = "";
	kb_model = "";
	kb_options = "grp:alt_space_toggle,caps:escape";
	kb_rules = "";

	follow_mouse = 1;

	sensitivity = 0;

	touchpad = {
	  natural_scroll = true;
	  middle_button_emulation = true;
	};
      };

      # gestures = {
      #   workspace_swipe = false;
      # };

      bind = [
        "$mainMod, Return, exec, $terminal"
        "$mainMod, Space, exec, $menu"
        "$mainMod, C, exec, $calc"
        "$mainMod SHIFT, Q, killactive,"
        "$mainMod SHIFT, Space, togglefloating,"
        "$mainMod SHIFT, E, exit,"
        "$mainMod, V, layoutmsg, preselect bottom"
        "$mainMod, B, layoutmsg, preselect right"
        "$mainMod ,F,fullscreen"
        
        "$mainMod, PRINT, exec, hyprshot -m region"
        
        "$mainMod, E, exec, $fileManager"
        "$mainMod, P, pseudo," # dwindle
        "$mainMod, J, togglesplit," # dwindlei
        
        # focus with mainMod + arrow keys
        "$mainMod, left, movefocus, l"
        "$mainMod, right, movefocus, r"
        "$mainMod, up, movefocus, u"
        "$mainMod, down, movefocus, d"

        "$mainMod SHIFT, right, swapwindow, r"
        "$mainMod SHIFT, left, swapwindow, l"
        "$mainMod SHIFT, down, swapwindow, d"
        "$mainMod SHIFT, up, swapwindow, u"

	", XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"

        # Switch workspaces with mainMod + [0-9]
        "bind = $mainMod, 1, workspace, 1"
        "bind = $mainMod, 2, workspace, 2"
        "bind = $mainMod, 3, workspace, 3"
        "bind = $mainMod, 4, workspace, 4"
        "bind = $mainMod, 5, workspace, 5"
        "bind = $mainMod, 6, workspace, 6"
        "bind = $mainMod, 7, workspace, 7"
        "bind = $mainMod, 8, workspace, 8"
        "bind = $mainMod, 9, workspace, 9"
        "bind = $mainMod, 0, workspace, 10"

        # Move active window to a workspace with mainMod + SHIFT + [0-9]
        "bind = $mainMod SHIFT, 1, movetoworkspace, 1"
        "bind = $mainMod SHIFT, 2, movetoworkspace, 2"
        "bind = $mainMod SHIFT, 3, movetoworkspace, 3"
        "bind = $mainMod SHIFT, 4, movetoworkspace, 4"
        "bind = $mainMod SHIFT, 5, movetoworkspace, 5"
        "bind = $mainMod SHIFT, 6, movetoworkspace, 6"
        "bind = $mainMod SHIFT, 7, movetoworkspace, 7"
        "bind = $mainMod SHIFT, 8, movetoworkspace, 8"
        "bind = $mainMod SHIFT, 9, movetoworkspace, 9"
        "bind = $mainMod SHIFT, 0, movetoworkspace, 10"

	
        # Example special workspace (scratchpad)
        "bind = $mainMod, S, togglespecialworkspace, magic"
        "bind = $mainMod SHIFT, S, movetoworkspace, special:magic"
        
        # Scroll through existing workspaces with mainMod + scroll
        "bind = $mainMod, mouse_down, workspace, e+1"
        "bind = $mainMod, mouse_up, workspace, e-1"

	# Lid Shut
	",switch:on:Lid Switch,exec,hyprlock"
      ];

      bindm = [
        "$mainMod, mouse:272, movewindow"
        "$mainMod, mouse:273, resizewindow"
      ];

      binde = [
        "$mainMod ALT, right, moveactive, 30 0"
        "$mainMod ALT, left, moveactive, -30 0"
        "$mainMod ALT, up, moveactive, 0 -30"
        "$mainMod ALT, down, moveactive, 0 30"
        "$mainMod CTRL, right, resizeactive, 10 0"
        "$mainMod CTRL, left, resizeactive, -10 0"
        "$mainMod CTRL, up, resizeactive, 0 -10"
        "$mainMod CTRL, down, resizeactive, 0 10"
        ",XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
        ",XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
        ",XF86MonBrightnessUp, exec, brightnessctl s +5%"
        ",XF86MonBrightnessDown, exec, brightnessctl s 5%-"
      ];

      bindl = [
        ",XF86AudioPlay, exec, playerctl play-pause" # the stupid key is called play , but it toggles
        ",XF86AudioNext, exec, playerctl next "
        ",XF86AudioPrev, exec, playerctl previous"
      ];

      windowrule = [

      ];

      windowrulev2 = [
        "suppressevent maximize, class:.*" # You'll probably like this.
      ];
    };
  };

  services.hypridle = {
    enable = true;

	settings = {
	  general = {
	    lock_cmd = "pidof hyprlock || hyprlock";
		before_sleep_cmd = "loginctl lock-session";
		after_sleep_cmd = "hyprctl dispatch dpms on";
	  };

	  listener = [
		{	
	      timeout = 150;
		  on-timeout = "brightnessctl -s set 10%";
		  on-resume = "brightnessctl -r";
		}
		{
		  timeout = 600;
		  on-timeout = "loginctl lock-session";
		}
		{
		  timeout = 660;
		  on-timeout = "hyprctl dispatch dpms off";
		  on-resume = "hyprctl dispatch dpms on";
		}
		{
		  timeout = 1800;
		  on-timeout = "systemctl suspend";
		}
	  ];
	};
  };

  # Hyprlock
  programs.hyprlock = {
    enable = true;

	sourceFirst = true;

	settings = {
	  source = [    
	    "$HOME/.cache/wal/colors-hyprland.conf"
	  ];

	  general = {
	    hide_cursor = false;
	  };

	  background = {
	    path = "screenshot";
	    blur_passes = 2;
	    contrast = 1;
	    brightness = 0.75;
	    vibrancy = 0.2;
	    vibrancy_darkness = 0.2;
	  };

	  input-field = {
	    size = "250, 60";
	    outline_thickness = 2;
	    dots_size = 0.2;
	    dots_spacing = 0.35;
	    dots_center = true;
	    outer_color = "rgba(0, 0, 0, 0)";
	    inner_color = "rgba(0, 0, 0, 0.5)";
	    font_color = "$foreground";
	    fade_on_empty = false;
	    rouding = -1;
	    check_color = "rgb(204, 136, 34)";
	    placeholder_text = ''<i><span foreground="##cdd6f4">Input Password...</span></i>'';
	    hide_input = false;
	    halign = "center";
	    valign = "center";
	  };

	  label = {
	    text = ''cmd[update:1000] echo "$(date +"%-I:%M")"'';
	    color = "$foreground";
	    font_size = 95;
	    font_family = "JetBrains Mono Extrabold";
	    position = "0, 200";
	    halign = "center";
	    valign = "center";
	  };	
	};
  };
}
