# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.kernelParams = [ "resume=/dev/disk/by-uuid/012657ba-cb85-4499-a818-86b4ee42c334" ];
  boot.resumeDevice = "/dev/disk/by-uuid/012657ba-cb85-4499-a818-86b4ee42c334";
  powerManagement.enable = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/bc3c7cbd-0e9a-4941-add8-4fd8fc197c9a";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EA48-3E05";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/83b04f40-42f8-4b8d-8831-16f7e9ab0e56";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/012657ba-cb85-4499-a818-86b4ee42c334"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
