# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.kernelParams = [ "resume=/dev/disk/by-uuid/38a3dc6c-7903-4d07-ada5-1c36244910c3" ];
  boot.resumeDevice = "/dev/disk/by-uuid/38a3dc6c-7903-4d07-ada5-1c36244910c3";
  powerManagement.enable = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e98727a3-5bca-42af-9ca7-ee3fc0342815";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/AE95-9FE9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e9551a12-f694-4e79-8380-befd18c7dd07";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/38a3dc6c-7903-4d07-ada5-1c36244910c3"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
