# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

	boot.kernelPackages = pkgs.linuxPackages_latest;

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.kernelParams = [ "resume=/dev/disk/by-uuid/cb5cf247-5ccf-4c08-a0f8-a8ea7403f6f1" ];
  boot.resumeDevice = "/dev/disk/by-uuid/cb5cf247-5ccf-4c08-a0f8-a8ea7403f6f1";
  powerManagement.enable = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/027c98f4-865a-40ec-b73d-0d9c30136a84";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A624-1E67";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/6b5794a5-46ba-4344-8f0b-2e48564bdf04";
      fsType = "ext4";
    };

	fileSystems."/mnt/Drive-2" =
		{ device = "/dev/disk/by-uuid/4030be52-ca10-4d21-81fe-edd07fd12488";
			fsType = "ext4";
		};

	fileSystems."/mnt/Drive-3" =
		{ device = "/dev/disk/by-uuid/4d117df2-b5c7-4494-af72-5e6200576889";
			fsType = "ext4";
		};

  swapDevices =
    [ { device = "/dev/disk/by-uuid/cb5cf247-5ccf-4c08-a0f8-a8ea7403f6f1"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
